### ISSUE TITLE
store.use should return scoped setter

### ISSUE THREAD

**Issue by odama626** [odama626/dawei#2]
store.use currently returns [state, global setter] it would be more intuitive if it returned a scoped setter as well

**Comment by odama626** [comment]
could possibly allow for string or array in use to allow for scoped setter, but set logic would have to be rewritten to account for scopes and it could possibly cause conflicts with atoms

ex:
```js


const [user, setUser] = store.use(`users.${userIndex}`);
const [loading, setLoading] = store.use('loading')
const [username, setUsername] = store.user(`users.${userIndex}.username`);
```

using arrays could also be a good idea, but I'm not sure how setters should be scoped for those yet
```js
const [{ username, age, sex }, setWhat] = store.user([
  `users.${userIndex}.username`,
  `users.${userIndex}.age`,
  `users.${userIndex}.sex`,
]);
```

**Comment by pixel9** [comment]
The current signature that returns the global setter seems novel but I can imagine it causing some confusion if multiple calls to `store.use()` ends up with multiple local variables that point to the global setter. I wouldn't have expected `store.use()` to return anything other than a slice of the state.

If you could get/set a state slice without introducing a messy selector syntax...that would be something. I think the template string syntax makes sense for the examples listed. It's terse and easy to convey intent. Are there cases where such a simple syntax wouldn't work? Would the format potentially get expensive to parse to figure out the setter logic?

For the case of the selector being an array, I would imagine an array of setters getting returned.
```js
const [[first, last], [setFirst, setLast]] = store.use([`users.${id}.first`, `users.${id}.last`]);
```
...or an array of value/setter pairs:
```js
const [[first, setFirst], [last, setLast]] = store.use([`users.${id}.first`, `users.${id}.last`]);
```

However, I'm not sure if this provides any benefit over just calling `store.use` multiple times in terms of readability.
```js
const [first, setFirst] = store.use(`users.${id}.first`);
const [last, setLast] = store.use(`users.${id}.last`);
```

**Comment by odama626** [comment]
the latest version can handle strings and arrays of strings but I don't believe that we should deal with handling arrays of strings in the future.... also, something I noticed more recently was using an optional chain string to a route that doesn't exist causes the setter to do the wrong thing.

I've been thinking about this a while and think I've possibly found a solution if we can get an efficient implementation for it

for example
```js
let store = createStore(() => {})

let [useNested, setNested] = store.use('nested.value');

// since nested is undefined then trying to set value should throw an error 
setNested('this should fail') 
// store {}


// note the optional chain notation ?.
let [useNested, setNested] = store.use(`nested?.value');

// since we used optional chain syntax this should succeed and recursively populate objects
setNested('this should succeed');
// store { nested: { value: 'this should succeed' } }
```

**Comment by odama626** [comment]
after some thought requiring a `?.` for creating undefined parent objects with a scoped setter would work inconsistently with the getter.

In light of keeping the api simple and concise, we should probably not support arrays for `.use` and maybe we should even get rid of createAtom since it is a fringe use case and createStore can fully support it's use cases.

**Comment by odama626** [comment]
optional chaining works with a string in dot syntax 'a.b.c' in getters now consistently, I believe the next step is to further simplify by removing atom subscriptions in initial state but that will be a breaking change. creating a new issue for that
